### ISSUE TITLE
amb-docker

### ISSUE THREAD

**Issue by dio99** [br0ziliy/amb-docker#4]
Hi 
i got it up and running after som issues with user and pwd for the db's
but im testing this to a mylaps AMB with version 4.5 software
get this issues on decode som values
amb_client_1  | Requesting Decoder Time
amb_client_1  | Waiting for DECODER timestamp
amb_client_1  | b'001c' record_type uknown
amb_client_1  | Traceback (most recent call last):
amb_client_1  |   File "/code/amb_client.py", line 87, in <module>
amb_client_1  |     main()
amb_client_1  |   File "/code/amb_client.py", line 52, in main
amb_client_1  |     if 'GET_TIME' == decoded_body['RESULT']['TOR']:
amb_client_1  | KeyError: 'TOR'
karts_db_1    | 2021-01-22 11:43:08 9 [Warning] Aborted connection 9 to db: 'karts' user: 'karts' host: '172.31.0.1' (Got an error reading communication packets)
amb-docker_amb_laps_1 exited with code 1
amb-docker_amb_client_1 exited with code 1

**Comment by br0ziliy** [comment]
This repository only hosts docker-compose file, please report amb-related issues in the upstream repo at https://github.com/vmindru/ambp3client
